name: "tf_matrix"
description: "Generate matrix"

inputs:
  regionName:
    description: 'The region to deploy to'
    required: false
    default: ''
  regionConfig:
      description: 'GitHUB Region config variable with deployment environment details'
      required: true
outputs:
  matrix:
    description: "Matrix object"
    value: ${{ steps.setmatrixobjects.outputs.matrix }}
runs:
  using: composite
  steps:
    - name: setmatrixobjects
      id: setmatrixobjects
      #Set the matrix environments based on region,additional environments can be updated in regionconfig variable 
      run: |
        envconfig=${{inputs.regionConfig}}
        if [ -z ${{github.event.inputs.regionName}} ] || [ ${{inputs.regionName}} == "All-Regions" ]; then
          echo "matrix=$(echo $envconfig|jq -c ['.[]| .[]'])" >> $GITHUB_OUTPUT
        else
          echo "matrix=$(echo $envconfig|jq -c [.${{inputs.regionName}}[]])" >> $GITHUB_OUTPUT
        fi
        echo $matrix
      shell: bash
    - run: | 
        echo matrixobject "$Matrix"
      env:
         MATRIX: ${{ steps.setmatrixobjects.outputs.matrix }}
      shell: bash