name: "tf_matrix"
description: "Generate matrix"

inputs:
  regionName:
    description: 'The region to deploy to'
    required: false
    type: string
    default: ''
  regionConfig:
      description: 'GitHUB Region config variable with deployment environment details'
      required: true
      type: string   
runs:
  using: composite
  steps:
    - name: setmatrixobjects
      id: setmatrixobjects
      outputs:
        matrix: ${{ steps.setmatrixobjects.outputs.matrix }}
      #Set the matrix environments based on region,additional environments can be updated in regionconfig variable 
      run: |
        envconfig=${{github.event.inputs.regionConfig}}
        if [ -z "${{github.event.inputs.regionName}}" ] || [ "${{github.event.inputs.regionName}}" == "All-Regions" ]; then
          echo "matrix=$(echo $envconfig|jq -c ['.[]| .[]'])" >> $GITHUB_OUTPUT
        else
          echo "matrix=$(echo $envconfig|jq -c [.${{github.event.inputs.regionName}}[]])" >> $GITHUB_OUTPUT
        fi
        echo $matrix
      shell: bash
