name: Saran

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
 GetBuildMetadata-GetBuildMetadata:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Get Build Metadata
    environment: development
    runs-on: ubuntu-latest
    steps:
    - name: Determining Build Number
      id: determineBuildNumber
      run: |-
         $buildId = "1.0"
      shell: pwsh
  
 Deploymentste0:
    name: AppDeployment
    needs: GetBuildMetadata-GetBuildMetadata
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          environment:
            - development
            - qa
            - cat
            - uat
    environment: ${{ matrix.environment }}
    
    steps:
        - name: Do something
          run: echo "Do something"
        
 PostDeploy:
    name: Post PostDeploy
    needs: GetBuildMetadata-GetBuildMetadata
           AppDeployment (${{ matrix.environment }})
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          environment:
            - development
            - qa
            - cat
            - uat
    environment: ${{ matrix.environment }}
    
    steps:
        - name: Do something
          run: echo "Do something post deploy"
