name: Saran

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
 GetBuildMetadata-GetBuildMetadata:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Get Build Metadata
    environment: development
    runs-on: ubuntu-latest
    steps:
    - name: Determining Build Number
      id: determineBuildNumber
      env:
        run: |-
         $buildId = "1.0"
      shell: pwsh
  
 Deploymentste0:
    name: App Deployment 
    needs: GetBuildMetadata-GetBuildMetadata
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          environment:
            - development
            - qa
            - cat
            - uat
    environment: ${{ matrix.environment }}
    
       
