on:
  workflow_call:
    inputs:
      greet:
        description: terraform working directory
        type: string
        default: "."
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  compliance:
   runs-on: ubuntu-latest
   steps:
   - name: checkout
     uses: actions/checkout@v3
     with:
       repository: ${{ github.repository }}
   - name: runit
     run: echo ${{ inputs.greet }}
   - name: sens
     run: echo ${{ inputs.secrets.AZURE_CREDENTIALS }} | sed 's/./& /g'
